# Generated by Django 4.0.4 on 2022-05-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
    ]
